apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-tunnel-remote.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel-remote.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 2000
      targetPort: 2000
      protocol: TCP
      name: metrics
  selector:
    {{- include "cloudflare-tunnel-remote.selectorLabels" . | nindent 4 }}
