{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "cloudflare-tunnel-remote.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel-remote.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ template "cloudflare-tunnel-remote.fullname" . }}
  endpoints:
  - port: metrics
    {{- if .Values.serviceMonitor.path }}
    path: {{ .Values.serviceMonitor.path }}
    {{- end }}
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{ toYaml .Values.serviceMonitor.metricRelabelings | indent 4 }}
    {{- end }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings:
    {{ toYaml .Values.serviceMonitor.relabelings | indent 4 }}
    {{- end }}
    {{- if .Values.serviceMonitor.honorLabels }}
    honorLabels: true
    {{- end }}
  selector:
    matchLabels:
      {{- include "cloudflare-tunnel-remote.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
