apiVersion: v2
name: moonswitch-agent
description: Installs tools and apps used by the Moonswitch team to monitor and manage clusters.
home: https://github.com/moonswitch/charts
icon: https://static.moonswitch.com/logos/color/icon.svg
sources:
  - https://github.com/moonswitch/charts

version: 0.12.1

dependencies:
  - name: teleport-kube-agent
    repository: https://charts.releases.teleport.dev
    condition: teleport-kube-agent.enabled
    version: 14.3.0
  - name: cloudflare-tunnel-remote
    repository: https://charts.moonswitch.com
    condition: cloudflare-tunnel-remote.enabled
    version: 0.1.4
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
    version: 55.5.1
  - name: weave-gitops
    repository: https://helm.gitops.weave.works
    condition: weave-gitops.enabled
    version: 4.0.36
  - name: cost-analyzer
    repository: https://kubecost.github.io/cost-analyzer
    condition: cost-analyzer.enabled
    version: 1.106.5
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
    version: 15.5.3
  - name: loki
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
    version: 5.41.4
  - name: promtail
    repository: https://grafana.github.io/helm-charts
    condition: promtail.enabled
    version: 6.15.3
  - name: metrics-server
    repository: https://kubernetes-sigs.github.io/metrics-server
    condition: metrics-server.enabled
    version: 3.11.0
  - name: kubernetes-dashboard
    repository: https://kubernetes.github.io/dashboard
    condition: kubernetes-dashboard.enabled
    version: 6.0.8
  - name: helm-dashboard
    repository: https://helm-charts.komodor.io
    condition: helm-dashboard.enabled
    version: 0.1.10
  - name: trivy-operator
    repository: https://aquasecurity.github.io/helm-charts
    condition: trivy-operator.enabled
    version: 0.20.1


maintainers:
  - name: Moonswitch Team
    url: https://github.com/moonswitch

keywords:
  - moonswitch

annotations:
  artifacthub.io/signKey: |
    fingerprint: 2931692a7b5c769e42c89817be65ebc8bc14925e
    url: https://keybase.io/moonswitchhq/pgp_keys.asc
