nameOverride: ""
fullnameOverride: ""

teleport-kube-agent:
  enabled: true
  proxyAddr: teleport.prd.moonswitch.io:443
  highAvailability:
    replicaCount: 3
    requireAntiAffinity: true
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
  roles: kube
  joinParams:
    method: "token"
    tokenName:
  extraLabels:
    clusterRole:
      "moonswitch.io/app": moonswitch-agent
    clusterRoleBinding:
      "moonswitch.io/app": moonswitch-agent
    role:
      "moonswitch.io/app": moonswitch-agent
    roleBinding:
      "moonswitch.io/app": moonswitch-agent
    config:
      "moonswitch.io/app": moonswitch-agent
    deployment:
      "moonswitch.io/app": moonswitch-agent
    pod:
      "moonswitch.io/app": moonswitch-agent
    podDisruptionBudget:
      "moonswitch.io/app": moonswitch-agent
    podSecurityPolicy:
      "moonswitch.io/app": moonswitch-agent
    secret:
      "moonswitch.io/app": moonswitch-agent
    serviceAccount:
      "moonswitch.io/app": moonswitch-agent

cloudflare-tunnel-remote:
  enabled: true

kube-prometheus-stack:
  enabled: true
  commonLabels:
    "moonswitch.io/app": moonswitch-agent

  alertmanager:
    alertmanagerSpec:
      routePrefix: /alertmanager
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 40Gi

  grafana:
    defaultDashboardsTimezone: browser
    grafana.ini:
      server:
        domain:
        root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
        serve_from_sub_path: true
      auth:
        disable_login_form: true
      auth.anonymous:
        enabled: true
        org_name: Moonswitch
        org_role: admin

  cleanPrometheusOperatorObjectNames: true

  prometheus:
    prometheusSpec:
      routePrefix: /prometheus
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 100Gi

  prometheus-node-exporter:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                  - fargate

weave-gitops:
  enabled: true
  replicaCount: 1
  podLabels:
    "moonswitch.io/app": moonswitch-agent
  additionalArgs:
    - --insecure-no-authentication-user=gitops-dashboard-user
    - --route-prefix=/gitops
