apiVersion: v1
kind: Secret
metadata:
  name: cluster-info
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moonswitch-agent.labels" . | nindent 4 }}
type: Opaque
data:
  tunnelToken: {{ .Values.cloudflareTunnelToken | base64 }}


