apiVersion: v1
kind: Secret
metadata:
  name: cluster-info
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moonswitch-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.cloudflareTunnelToken }}
  tunnelToken: {{ .Values.cloudflareTunnelToken | b64enc }}
  {{- end }}
  {{- if .Values.teleportJoinToken }}
  auth-token: {{ .Values.teleportJoinToken | b64enc }}
  {{- end }}

