apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moonswitch-agent.labels" . | nindent 4 }}
data:
  CLUSTER_NAME: {{ .Values.clusterName | quote }}
  CLIENT_NAME: {{ .Values.clientName | quote }}
