clusterName: ci-testing
clientName: test
teleport-kube-agent:
  kubeClusterName: ci-test
  highAvailability:
    replicaCount: 1
    requireAntiAffinity: false
    podDisruptionBudget:
      enabled: false
metrics-server:
  enabled: true
  args:
    - --kubelet-insecure-tls
  replicas: 1
  podDisruptionBudget: {}
  addonResizer:
    enabled: false
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
  affinity: {}
